name: Functions
on:
  push:
    branches:
      - main
    paths:
      - "functions/**/*"
      - ".firebaserc"
      - "firebase.json"
      - ".github/workflows/functions.yml"

jobs:
  deploy:
    name: Firebase deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --prefix functions
      - name: Lint
        run: npm run lint --prefix functions
      - name: Build
        run: npm run build --prefix functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --message \"${{ github.event.head_commit.hash }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
